### ISSUE TITLE
Rearrange the UI and merge the apply button

### ISSUE THREAD

**Issue by chraac** [FIFARenderZ/EPYC-Rome-Overclock#1]
Currently we have 3 or more apply button, thus we need to apply multi-times, can we combine them as 1, so that we can change the setting multi times and then apply just 1 times?

**Comment by chraac** [comment]
I fork this repo and make a refactoring version in the forked repo, will merge back when finished:
[chraac/EPYC-Rome-Overclock](https://github.com/chraac/EPYC-Rome-Overclock)

**Comment by chraac** [comment]
Several features I will add: 
- Unified the Apply button, this means you can change all values then apply once.
- Save/Load settings

**Comment by FIFARenderZ** [comment]
Go ahead! Excited to see what you can make of it :)
